### ISSUE TITLE
PublishMessageResponse Empty

### ISSUE THREAD

**Issue by Lamby123** [zeebe-io/zeebe-client-csharp#88] opened 2020-01-07 16:16 UTC
The PublishMessageResponse class contains no properties to determine whether the response was success or failure. 

**To Reproduce**
1. Publish  a new message using the NewPublishMessageCommand() 
2. Await the result 
3. Retrieve the PublishMessageResponse object
4. This object has no properties. 

**Expected behavior**
1. The Publish Message Response object should have enough information in it to determine success or failure and a reason for failure. 

Thanks 
James

**Comment by Lamby123** [comment] 2020-01-07 16:17
The same issue is present with the UpdateRetriesResponse  however I have not yet needed to use that particular response.

**Comment by Zelldon** [comment] 2020-01-07 16:39
Hey @Lamby123 ,

these response objects are only returned on success. On failure an exception is thrown.

**Comment by Lamby123** [comment] 2020-01-07 16:46
Hi Zelldon, 

In the case where we are sending back a correlation key should it return an error if there is no workflow instance matching the criteria of the NewPublishMessageCommand(). 

For example: 
client.NewPublishMessageCommand()
                        .MessageName("payment-received")
                        .CorrelationKey("12345")


When we run the above code and the message name "payment-received" does not exist, or the correlation key "12345" does not exist this it does not throw an error. It returns an empty "PublishMessageResponse" object. 

Regards, 
James

**Comment by Zelldon** [comment] 2020-01-07 18:44
Hey thanks for the quick reply.

Please note that messages are buffered in Zeebe based on a specified TTL. The C# Client uses an default TTL setting. This means when a message is published it can happen that no instance for this message exist, but based on the TTL it is buffered and can be correlated later. Please take a look at the corresponding documentation https://docs.zeebe.io/reference/message-correlation.html

 I'm wondering what kind of error you get with zbctl? Could you please share the command you execute and the error you get?

Greets
Chris

**Comment by Lamby123** [comment] 2020-01-08 10:08
Hi Chris, 

I think the confusion here is related to the TTL buffering. 
We were expecting to receive errors under the following circumstances: 
1. The message name provided does not exist. 
2. The correlation key provided does not exist. 

In the example below: 
             await client.NewPublishMessageCommand()
                   .MessageName("invalid-message-name")
                   .CorrelationKey("invalid-correlation-key")
                   .Send();

Using the example above, I have looked at the documentation you have linked and understand that correlation key "invalid-correlation-key" could be sent in for a workflow instance that does not yet exist, however if there is no message anywhere on any workflow with the name "invalid-message-name" we would have expected to receive an error. 

Perhaps I am misunderstanding how it all hangs together but if we are sending in a message that will never be resolved due to the message name being invalid should it not return an error instead of sitting there forever?

Is there a setting we could use whereby the above behaviour is represented?


P.S. Please ignore my previous comment about the zbctl returning an error message for the scenario I mentioned - I was thinking of the create instance command which does return an error if the workflow does not exist.

**Comment by Zelldon** [comment] 2020-01-08 12:48
> Perhaps I am misunderstanding how it all hangs together but if we are sending in a message that will never be resolved due to the message name being invalid should it not return an error instead of sitting there forever?

It will not hang forever since it is deleted after the TTL.

> Is there a setting we could use whereby the above behaviour is represented?

Not far as I know. The benefit of that is that you do not have race conditions where the workflow instance does not have reached the catched event, when the message was published. The workflow instance can be delayed and the message can be published early without any problems. 

What is the use case behind your questions? What do you want to achieve?

**Comment by jwulf** [comment] 2020-01-09 16:53
> I'm wondering what kind of error you get with zbctl? Could you please share the command you execute and the error you get?

I also would like to see this. Are you sure it does this?

**Comment by jwulf** [comment] 2020-01-09 16:59
> Using the example above, I have looked at the documentation you have linked and understand that correlation key "invalid-correlation-key" could be sent in for a workflow instance that does not yet exist, however if there is no message anywhere on any workflow with the name "invalid-message-name" we would have expected to receive an error.

The broker reasons over active message subscriptions, not workflow instances or definitions. 

You could code the broker to reason over the complete set of potential correlations, but you should probably do that at design time, no?

Like this: https://github.com/StephenOTT/Workflow-Linter

**Comment by Lamby123** [comment] 2020-01-10 10:43
Sorry for the late reply. I was out of the office yesterday. 

> What is the use case behind your questions? What do you want to achieve?

We have a few scenarios which will require manual user approval. 
For example, at the end of a workflow we might need the risk manager to look over the information and click approve to state that he/she is happy with the outcome of the flow. 

For this scenario we were looking to use a message receive event and would send in the correlation key to progress the workflow once the end user has approved. 


> I also would like to see this. Are you sure it does this? 

Apologies - I was mistaken on this point. I was confusing the correlation key command with the create new instance command. 
The create new instance command does return an error when there is no workflow with the specified name, however the correlation key command does not return an error when there is no matching message name. 

> The broker reasons over active message subscriptions, not workflow instances or definitions.

> You could code the broker to reason over the complete set of potential correlations, but you should probably do that at design time, no?


It was more a question of whether Zeebe was functionally capable of handling such a scenario - it just seemed odd that we could send in a correlation key for a message that has not been defined in any workflow without receiving an error, but yes this is something we can handle at design time if Zeebe offers that functionality. I think we thought of this as something that would be default behaviour (or a setting on the client) rather than something we have to code ourselves.

**Comment by berndruecker** [comment] 2020-01-14 08:11
So you are basically doing Human Task Management - right? We plan to support that directly later this year, then you will have proper User Tasks from BPMN - and there of course you can only complete a task if it is still open. 

Just a quick thought: You could also use normal Service Tasks (instead of messages) - then the Zeebe Job is kind of your user task - you can only complete it if it is still open. Does that make sense?

**Comment by Lamby123** [comment] 2020-01-14 09:35
> Just a quick thought: You could also use normal Service Tasks (instead of messages) - then the Zeebe 

> Job is kind of your user task - you can only complete it if it is still open. Does that make sense?


That does make sense however I question whether it is advisable to have such long running tasks. 
If we have a Zeebe client that pauses whilst it waits for user interaction - it could potentially be waiting for days before the task finishes to completion. 

Do you have an example / best practise for using service tasks for such a scenario? - blocking the thread for potentially a long period of time seems inappropriate. 

I question why you are steering away from using correlation keys for this use case? Perhaps my lack of BPMN experience is showing but it feels to me as though the use of correlation keys would be an effective way to manage a long wait for user interaction?

**Comment by Zelldon** [comment] 2020-05-22 06:18
To came back to the original reported issue it is not a bug in the client, which is the reason why I will close this. If you disagree feel free to reopen this, then we can discuss this again. Furthermore feel free to reach us via slack or the forum if you have further questions.

**Closed by Zelldon** 2020-05-22 06:18 UTC
Labels: bug
