### ISSUE TITLE
Creating a lot of serviceTask workers with HandlerThreads > 1 slows down loading workflow BPMNs

### ISSUE THREAD

**Issue by MrRickwi** [zeebe-io/zeebe-client-csharp#164] opened 2020-08-27 15:39 UTC
**Describe the bug**
We use the new feature which allows setting the HandlerThread count. However, it seems that the client does not use proper task handling features of C#, but instead reserves a task for every HandlerThread required. That in turn slows down loading of BPMNs (NewDeployCommand) to being nearly unusable.

**To Reproduce**
1. Create some ServiceTasks, set HandlerThreads to a reasonable big value
2. Load a BPMN using NewDeployCommand()
3. Measure the time it takes to load the workflow and get the result

**Expected behavior**
Should be as fast as in version 0.16.1

**Enviroment (please complete the following information):**
 - OS: Windows
 - Version 0.17.0

**Additional context**
My measurements for loading workflows:
- In 0.16.1: < 1 second for 8 workflows
- In 0.17.0 with 10 ServiceTasks with 1 HandlerThread: 4 seconds
- In 0.17.0 with 10 ServiceTasks with 2 HandlerThread: 13 seconds
- In 0.17.0 with 10 ServiceTasks with 3 HandlerThread: 23 seconds

**Comment by Zelldon** [comment] 2020-08-27 16:53
Hey @MrRickwi 

thanks for reporting that.
I'm not 100% sure whether I get the issue.

Are you saying that the response of the deployment takes longer? Have you some example code to reproduce this?

Greets
Chris

**Comment by MrRickwi** [comment] 2020-08-28 06:50
Yes, the response takes way longer. Here some code to demonstrate it. You could remove HandlerThreads and run it with 0.16.1 to see how it performs there:

`
        [Test]
        public void PerformanceTest()
        {
            for (var i = 0; i < 10; i++)
            {
                var worker = WorkflowEngine.Instance.NewWorker()
                    .JobType($"serviceTask{i}")
                    .Handler((client, job) => { })
                    .HandlerThreads(5)
                    .MaxJobsActive(10)
                    .PollInterval(TimeSpan.FromMilliseconds(100))
                    .Timeout(TimeSpan.FromSeconds(30))
                    .Open();

                Console.WriteLine($@"{DateTime.Now}: Created worker serviceTask{i}");
            }

            var workflows = WorkflowEngine.Instance.NewDeployCommand()
                .AddResourceStream(
                    Assembly.GetExecutingAssembly()
                        .GetManifestResourceStream("POC.Worker.Zeebe.Tests.Workflows.Test.bpmn"),
                    "Test.bpmn")
                .Send()
                .GetAwaiter()
                .GetResult();

            Console.WriteLine($@"{DateTime.Now}: Loaded workflows {JsonConvert.SerializeObject(workflows)}");
        }
`

Assume that the setup of the test sets WorkflowEngine.Instance like

`
            Instance = ZeebeClient.Builder()
                .UseLoggerFactory(loggerFactory ?? new NLogLoggerFactory())
                .UseGatewayAddress(gatewayAddress)
                .UsePlainText()
                .Build();
`

It seems that .NET task handling is massively disturbed by pre-allocating tasks - at least if they are not marked as long-running. See TaskCreationOptions for details.

**Comment by Zelldon** [comment] 2020-08-28 07:09
For me this is kind of expected, since you put much pressure on the broker. Lets talk about your setup.

You have 10 active jobs and 5 threads, which working concurrently on them. We have an poll thread which will try to poll after 100 ms (pollInterval) if the job queue is smaller then maxActivateJobs * 0.6. In your case 6. So if you have less then 6 jobs in your active working queue it will poll again for new jobs. Since your job handler is empty this will immediately happen, so every 100 ms the job worker will poll for new jobs. This means it will send an job command to the broker. The question here is are there enough jobs to work on? If not, then normally I would expect that long polling should kick in at the gateway.

If you have enough jobs to work on then you will overload the broker with work. It then of course depends how your broker is setup up. Do you have one partition or multiple? Say if you have one partition then everything ends in one append only log, which needs to be processed by one stream processor. Responses are only send if the command is committed by consensus and processed by the stream processor. For me it makes sense that deployments can take longer if the log is longer, since you have more activation commands in between.

**Comment by MrRickwi** [comment] 2020-08-28 14:48
It is really not kind of expected: The example does not create any workflow, but only creates service tasks handlers that potentially would be able to handle 10 different service tasks, each of them in 5 threads. Nothing which should overload a broker. And the created service tasks in turn delay loading a workflow which is not expected at all.

**Comment by MrRickwi** [comment] 2020-08-28 15:07
Made a local test by replacing Task.Run(async ( ... ) => {}, cancellationToken) with Task.Factory.StartNew(async delegate { ... }, cancellationToken, TaskCreationOptions.LongRunning) in JobWorker.StartPollerThread and JobWorker.StartHandlerThreads. Works as expected, everything is fast again.

**Comment by Zelldon** [comment] 2020-08-28 15:09
Thanks @MrRickwi I will take a look at this. Could you explain me the difference or the implications of this?

**Comment by MrRickwi** [comment] 2020-08-28 15:15
Yes: .NET throttles the creation of tasks in the thread pool if there are too much tasks created - as long as these tasks are not marked as long running. Long running tasks allow the thread pool to increase. Task.Run() is only meant for short running tasks and has not the option to mark tasks as long running. Task.Factory.StartNew is not so easy to use, but has more options.

However, I think pre-allocating tasks is not a good idea, instead the handler tasks should only be created if they are needed. I'm currently looking into the TPL (Task Parallels Library) on better handling of polling and executing with certain limits.

**Comment by Zelldon** [comment] 2020-08-28 16:19
Thanks @MrRickwi 

Yeah before I implemented that this way I also read about the Task scheduling but it felt weird to create so many tasks as activated jobs. I wanted to limit the created threads/tasks somehow and thought that it would be cool for the user to have control over it. But maybe this is done implicit via the Task scheduler then already? Tbh I'm not that experienced with the Task scheduling in .net, since I coming from Java and this is how I would do that normally there (with a Threadpool).

I'm happy for every advise and tip I can get about how it is normally done in the .net world :) 

I will revise the implementation.

Thanks and Greets
Chris

**Closed** 2020-09-16 20:18 UTC
Labels: bug

**Comment by Zelldon** [comment] 2020-09-24 09:12
Hey @MrRickwi 

the latest release https://github.com/zeebe-io/zeebe-client-csharp/releases/tag/0.18.0 contains your contribution!
Thanks again :)

Greets
Chris

**Comment by MrRickwi** [comment] 2020-09-27 13:04
Thanks. Didn't answer a while because I was in holidays. Will test that next week. Greets back
